---
kind: Secret
apiVersion: v1
metadata:
  name: dex
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.yaml: |
    issuer: {{ .Values.dex.config.issuer }}
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      # http: 0.0.0.0:5556
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/ssl/tls.crt
      tlsKey: /etc/dex/ssl/tls.key
    # Configuration for telemetry
    telemetry:
      https: 0.0.0.0:5558   
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: {{ .Values.dex.config.clientid }}
        clientSecret: {{ .Values.dex.config.clientSecret }}
        redirectURI: {{ template "connector.redirectUrl" . }}
    staticClients:
    - id: {{ .Values.dex.config.clientid }}
      redirectURIs:
      - {{ .Values.dex.config.staticClient.redirectUrl }}
      name: 'Argo workflow'
      SecretEnv: CLIENT_SECRET
    enablePasswordDB: true