apiVersion: v1
stringData:
  client-id: {{ .Values.dex.config.clientid }}
  client-secret: {{ .Values.dex.config.clientSecret }}
kind: Secret
type: Opaque
metadata:
  name: argo-workflows-sso
  namespace: {{ .Release.Namespace }}